-- ══════════════════════════════════════════════════════════════════════════
-- Met à jour le champ "region" de la table evenements pour TOUTES les
-- grandes villes et communes des 13 régions métropolitaines françaises.
--
-- Comparaison insensible aux accents ET à la casse via unaccent(lower(...)).
-- Chaque commune composée est listée avec et sans tiret (ex: 'lège-cap-ferret'
-- ET 'lege cap ferret') car la casse d'origine de la colonne "ville" peut
-- varier selon la saisie utilisateur.
--
-- Les lignes déjà associées à une ville non reconnue conservent leur région
-- actuelle (ELSE region).
-- ══════════════════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS unaccent;

UPDATE evenements
SET region = CASE

  -- ─── Île-de-France (75, 77, 78, 91, 92, 93, 94, 95) ───────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'paris',
    'boulogne-billancourt', 'boulogne billancourt',
    'saint-denis', 'saint denis',
    'argenteuil',
    'montreuil',
    'nanterre',
    'vitry-sur-seine', 'vitry sur seine',
    'creteil',
    'aubervilliers',
    'aulnay-sous-bois', 'aulnay sous bois',
    'colombes',
    'asnieres-sur-seine', 'asnieres sur seine',
    'rueil-malmaison', 'rueil malmaison',
    'champigny-sur-marne', 'champigny sur marne',
    'saint-maur-des-fosses', 'saint maur des fosses',
    'drancy',
    'issy-les-moulineaux', 'issy les moulineaux',
    'noisy-le-grand', 'noisy le grand',
    'versailles',
    'antony',
    'ivry-sur-seine', 'ivry sur seine',
    'clichy',
    'cergy',
    'pontoise',
    'levallois-perret', 'levallois perret',
    'neuilly-sur-seine', 'neuilly sur seine',
    'sarcelles',
    'le-blanc-mesnil', 'le blanc mesnil',
    'evry', 'evry-courcouronnes', 'evry courcouronnes',
    'meaux',
    'melun',
    'fontainebleau',
    'chelles',
    'mantes-la-jolie', 'mantes la jolie',
    'massy',
    'sartrouville',
    'corbeil-essonnes', 'corbeil essonnes',
    'la-courneuve', 'la courneuve',
    'bondy',
    'franconville',
    'garges-les-gonesse', 'garges les gonesse',
    'savigny-sur-orge', 'savigny sur orge',
    'gennevilliers',
    'villejuif',
    'epinay-sur-seine', 'epinay sur seine',
    'pantin',
    'clamart',
    'houilles',
    'taverny',
    'saint-germain-en-laye', 'saint germain en laye',
    'vincennes',
    'maisons-alfort', 'maisons alfort',
    'alfortville',
    'ermont',
    'meudon',
    'chatenay-malabry', 'chatenay malabry',
    'saint-ouen-sur-seine', 'saint ouen sur seine', 'saint-ouen', 'saint ouen',
    'bagneux',
    'bobigny',
    'cachan',
    'montrouge',
    'malakoff',
    'bourg-la-reine', 'bourg la reine',
    'plaisir',
    'viry-chatillon', 'viry chatillon',
    'athis-mons', 'athis mons',
    'brunoy',
    'montfermeil',
    'coulommiers',
    'provins',
    'rambouillet',
    'dourdan',
    'etampes',
    'poissy',
    'conflans-sainte-honorine', 'conflans sainte honorine',
    'acheres'
  ) THEN 'Île-de-France'

  -- ─── Auvergne-Rhône-Alpes (01, 03, 07, 15, 26, 38, 42, 43, 63, 69, 73, 74) ─
  WHEN unaccent(lower(trim(ville))) IN (
    'lyon',
    'villeurbanne',
    'saint-etienne', 'saint etienne',
    'grenoble',
    'clermont-ferrand', 'clermont ferrand',
    'annecy',
    'chambery',
    'valence',
    'vienne',
    'bourgoin-jallieu', 'bourgoin jallieu',
    'roanne',
    'montelimar',
    'romans-sur-isere', 'romans sur isere',
    'aix-les-bains', 'aix les bains',
    'annemasse',
    'thonon-les-bains', 'thonon les bains',
    'sallanches',
    'chamonix-mont-blanc', 'chamonix mont blanc', 'chamonix',
    'evian-les-bains', 'evian les bains',
    'albertville',
    'bourg-en-bresse', 'bourg en bresse',
    'oyonnax',
    'vichy',
    'moulins',
    'cusset',
    'montlucon',
    'riom',
    'issoire',
    'thiers',
    'le-puy-en-velay', 'le puy en velay',
    'aurillac',
    'saint-chamond', 'saint chamond',
    'firminy',
    'rive-de-gier', 'rive de gier',
    'privas',
    'aubenas',
    'gap',
    'briancon',
    'echirolles',
    'saint-martin-d-heres', 'saint martin d heres',
    'voiron',
    'meylan',
    'fontaine',
    'vaulx-en-velin', 'vaulx en velin',
    'venissieux',
    'rillieux-la-pape', 'rillieux la pape',
    'caluire-et-cuire', 'caluire et cuire',
    'decines-charpieu', 'decines charpieu',
    'saint-priest', 'saint priest',
    'tassin-la-demi-lune', 'tassin la demi lune',
    'oullins',
    'givors',
    'tarare',
    'feurs',
    'montbrison',
    'saint-vallier', 'saint vallier',
    'tournon-sur-rhone', 'tournon sur rhone',
    'la-mure', 'la mure',
    'crest',
    'amberieu-en-bugey', 'amberieu en bugey',
    'bellegarde-sur-valserine', 'bellegarde sur valserine',
    'cluses',
    'passy',
    'megeve',
    'saint-jean-de-maurienne', 'saint jean de maurienne',
    'modane',
    'ugine'
  ) THEN 'Auvergne-Rhône-Alpes'

  -- ─── Nouvelle-Aquitaine (16, 17, 19, 23, 24, 33, 40, 47, 64, 79, 86, 87) ──
  WHEN unaccent(lower(trim(ville))) IN (
    'bordeaux',
    'pessac',
    'merignac',
    'talence',
    'arcachon',
    'libourne',
    'gradignan',
    'lege-cap-ferret', 'lege cap ferret',
    'andernos-les-bains', 'andernos les bains',
    'biganos',
    'le-bouscat', 'le bouscat',
    'begles',
    'villenave-d-ornon', 'villenave d ornon',
    'blanquefort',
    'floirac',
    'cenon',
    'bruges',
    'limoges',
    'poitiers',
    'biarritz',
    'bayonne',
    'anglet',
    'pau',
    'la-rochelle', 'la rochelle',
    'niort',
    'agen',
    'angouleme',
    'perigueux',
    'brive-la-gaillarde', 'brive la gaillarde',
    'bergerac',
    'rochefort',
    'saintes',
    'cognac',
    'royan',
    'saint-jean-de-luz', 'saint jean de luz',
    'hendaye',
    'bidart',
    'dax',
    'mont-de-marsan', 'mont de marsan',
    'villeneuve-sur-lot', 'villeneuve sur lot',
    'marmande',
    'nerac',
    'oloron-sainte-marie', 'oloron sainte marie',
    'sarlat-la-caneda', 'sarlat la caneda',
    'coutras',
    'gueret',
    'tulle',
    'ussel',
    'chatellerault',
    'thouars',
    'bressuire',
    'parthenay',
    'jonzac',
    'montmorillon',
    'bellac',
    'saint-junien', 'saint junien',
    'panazol',
    'boulazac',
    'terrasson-lavilledieu', 'terrasson lavilledieu',
    'gujan-mestras', 'gujan mestras',
    'la-teste-de-buch', 'la teste de buch',
    'ares',
    'lacanau',
    'soulac-sur-mer', 'soulac sur mer',
    'langon',
    'sainte-foy-la-grande', 'sainte foy la grande'
  ) THEN 'Nouvelle-Aquitaine'

  -- ─── Occitanie (09, 11, 12, 30, 31, 32, 34, 46, 48, 65, 66, 81, 82) ───────
  WHEN unaccent(lower(trim(ville))) IN (
    'toulouse',
    'montpellier',
    'nimes',
    'perpignan',
    'beziers',
    'narbonne',
    'carcassonne',
    'albi',
    'montauban',
    'tarbes',
    'castres',
    'sete',
    'ales',
    'colomiers',
    'tournefeuille',
    'blagnac',
    'muret',
    'castanet-tolosan', 'castanet tolosan',
    'balma',
    'cugnaux',
    'ramonville-saint-agne', 'ramonville saint agne',
    'lourdes',
    'cahors',
    'rodez',
    'mende',
    'foix',
    'auch',
    'figeac',
    'millau',
    'castelsarrasin',
    'moissac',
    'agde',
    'frontignan',
    'lunel',
    'pezenas',
    'lodeve',
    'bagnols-sur-ceze', 'bagnols sur ceze',
    'uzes',
    'prades',
    'ceret',
    'argeles-sur-mer', 'argeles sur mer',
    'canet-en-roussillon', 'canet en roussillon',
    'saint-cyprien', 'saint cyprien',
    'pamiers',
    'lavelanet',
    'mazamet',
    'gaillac',
    'graulhet',
    'saint-gaudens', 'saint gaudens',
    'revel',
    'villefranche-de-rouergue', 'villefranche de rouergue',
    'decazeville',
    'gruissan',
    'port-la-nouvelle', 'port la nouvelle',
    'limoux',
    'castelnaudary',
    'lezignan-corbieres', 'lezignan corbieres',
    'saint-orens-de-gameville', 'saint orens de gameville',
    'plaisance-du-touch', 'plaisance du touch',
    'saint-jean', 'saint jean',
    'carbonne'
  ) THEN 'Occitanie'

  -- ─── Pays de la Loire (44, 49, 53, 72, 85) ────────────────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'nantes',
    'angers',
    'le-mans', 'le mans',
    'saint-nazaire', 'saint nazaire',
    'cholet',
    'laval',
    'la-roche-sur-yon', 'la roche sur yon',
    'saint-herblain', 'saint herblain',
    'reze',
    'saint-sebastien-sur-loire', 'saint sebastien sur loire',
    'orvault',
    'vertou',
    'sable-sur-sarthe', 'sable sur sarthe',
    'la-fleche', 'la fleche',
    'mayenne',
    'chateaubriant',
    'ancenis',
    'clisson',
    'machecoul',
    'pornic',
    'saint-brevin-les-pins', 'saint brevin les pins',
    'la-baule-escoublac', 'la baule escoublac', 'la baule',
    'guerande',
    'savenay',
    'chateau-gontier', 'chateau gontier',
    'segre',
    'evron',
    'mamers',
    'la-ferte-bernard', 'la ferte bernard',
    'allonnes',
    'coulaines',
    'change',
    'arnage',
    'les-herbiers', 'les herbiers',
    'les-sables-d-olonne', 'les sables d olonne',
    'challans',
    'fontenay-le-comte', 'fontenay le comte',
    'lucon',
    'montaigu-vendee', 'montaigu vendee', 'montaigu',
    'pouzauges',
    'trelaze',
    'avrille',
    'bouchemaine',
    'beaupreau-en-mauges', 'beaupreau en mauges', 'beaupreau',
    'saumur',
    'segre-en-anjou-bleu', 'segre en anjou bleu',
    'doue-en-anjou', 'doue en anjou', 'doue la fontaine',
    'bauge-en-anjou', 'bauge en anjou', 'bauge'
  ) THEN 'Pays de la Loire'

  -- ─── Grand Est (08, 10, 51, 52, 54, 55, 57, 67, 68, 88) ───────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'strasbourg',
    'reims',
    'metz',
    'mulhouse',
    'nancy',
    'colmar',
    'troyes',
    'epinal',
    'verdun',
    'thionville',
    'sarreguemines',
    'haguenau',
    'charleville-mezieres', 'charleville mezieres',
    'chalons-en-champagne', 'chalons en champagne',
    'chaumont',
    'saint-dizier', 'saint dizier',
    'forbach',
    'sarrebourg',
    'saverne',
    'selestat',
    'illkirch-graffenstaden', 'illkirch graffenstaden',
    'schiltigheim',
    'wissembourg',
    'molsheim',
    'obernai',
    'epernay',
    'vitry-le-francois', 'vitry le francois',
    'sedan',
    'revin',
    'rethel',
    'langres',
    'saint-avold', 'saint avold',
    'sarralbe',
    'bitche',
    'freyming-merlebach', 'freyming merlebach',
    'montigny-les-metz', 'montigny les metz',
    'hagondange',
    'hayange',
    'longwy',
    'toul',
    'luneville',
    'pont-a-mousson', 'pont a mousson',
    'saint-die-des-vosges', 'saint die des vosges',
    'remiremont',
    'gerardmer',
    'neufchateau',
    'mirecourt',
    'vandoeuvre-les-nancy', 'vandoeuvre les nancy',
    'essey-les-nancy', 'essey les nancy',
    'tomblaine',
    'jarville-la-malgrange', 'jarville la malgrange',
    'bar-le-duc', 'bar le duc',
    'commercy',
    'vouziers',
    'sezanne'
  ) THEN 'Grand Est'

  -- ─── Hauts-de-France (02, 59, 60, 62, 80) ─────────────────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'lille',
    'amiens',
    'roubaix',
    'tourcoing',
    'dunkerque',
    'valenciennes',
    'calais',
    'boulogne-sur-mer', 'boulogne sur mer',
    'arras',
    'beauvais',
    'compiegne',
    'saint-quentin', 'saint quentin',
    'soissons',
    'laon',
    'cambrai',
    'douai',
    'lens',
    'henin-beaumont', 'henin beaumont',
    'maubeuge',
    'denain',
    'villeneuve-d-ascq', 'villeneuve d ascq',
    'marcq-en-baroeul', 'marcq en baroeul',
    'wattrelos',
    'armentieres',
    'bethune',
    'lievin',
    'noyelles-godault', 'noyelles godault',
    'saint-omer', 'saint omer',
    'berck',
    'le-touquet-paris-plage', 'le touquet paris plage', 'le touquet',
    'hazebrouck',
    'merville',
    'aire-sur-la-lys', 'aire sur la lys',
    'montreuil-sur-mer', 'montreuil sur mer',
    'etaples',
    'abbeville',
    'albert',
    'peronne',
    'chantilly',
    'senlis',
    'creil',
    'noyon',
    'clermont',
    'chauny',
    'tergnier',
    'gauchy',
    'hirson',
    'chateau-thierry', 'chateau thierry',
    'saint-gobain', 'saint gobain',
    'vervins',
    'guise',
    'fourmies',
    'avesnes-sur-helpe', 'avesnes sur helpe',
    'le-cateau-cambresis', 'le cateau cambresis'
  ) THEN 'Hauts-de-France'

  -- ─── Bretagne (22, 29, 35, 56) ─────────────────────────────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'rennes',
    'brest',
    'quimper',
    'lorient',
    'vannes',
    'saint-malo', 'saint malo',
    'saint-brieuc', 'saint brieuc',
    'concarneau',
    'douarnenez',
    'morlaix',
    'guingamp',
    'lannion',
    'dinan',
    'dinard',
    'redon',
    'fougeres',
    'vitre',
    'pontivy',
    'auray',
    'lanester',
    'ploemeur',
    'quimperle',
    'hennebont',
    'landerneau',
    'plougastel-daoulas', 'plougastel daoulas',
    'guipavas',
    'chateaulin',
    'carhaix-plouguer', 'carhaix plouguer',
    'pont-l-abbe', 'pont l abbe',
    'bain-de-bretagne', 'bain de bretagne',
    'chateaugiron',
    'betton',
    'cesson-sevigne', 'cesson sevigne',
    'saint-gregoire', 'saint gregoire',
    'liffre',
    'janze',
    'pace',
    'bruz',
    'guichen',
    'plouzane',
    'gouesnou',
    'plabennec',
    'lesneven',
    'ploudalmezeau',
    'saint-pol-de-leon', 'saint pol de leon',
    'roscoff',
    'treguier',
    'paimpol',
    'perros-guirec', 'perros guirec',
    'plerin',
    'plouha',
    'matignon',
    'cancale',
    'combourg',
    'tinteniac',
    'montfort-sur-meu', 'montfort sur meu',
    'ploermel',
    'malestroit',
    'la-gacilly', 'la gacilly',
    'questembert',
    'muzillac',
    'sarzeau',
    'grand-champ', 'grand champ',
    'locmine',
    'baud',
    'gourin'
  ) THEN 'Bretagne'

  -- ─── Normandie (14, 27, 50, 61, 76) ────────────────────────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'le-havre', 'le havre',
    'rouen',
    'caen',
    'evreux',
    'cherbourg-en-cotentin', 'cherbourg en cotentin', 'cherbourg',
    'saint-etienne-du-rouvray', 'saint etienne du rouvray',
    'alencon',
    'flers',
    'avranches',
    'granville',
    'coutances',
    'saint-lo', 'saint lo',
    'bayeux',
    'dieppe',
    'elbeuf',
    'sotteville-les-rouen', 'sotteville les rouen',
    'vernon',
    'louviers',
    'val-de-reuil', 'val de reuil',
    'gisors',
    'lisieux',
    'honfleur',
    'deauville',
    'trouville-sur-mer', 'trouville sur mer',
    'pont-l-eveque', 'pont l eveque',
    'falaise',
    'vire-normandie', 'vire normandie', 'vire',
    'argentan',
    'l-aigle', 'l aigle',
    'mortagne-au-perche', 'mortagne au perche',
    'verneuil-sur-avre', 'verneuil sur avre',
    'conches-en-ouche', 'conches en ouche',
    'bernay',
    'pont-audemer', 'pont audemer',
    'fecamp',
    'yvetot',
    'bolbec',
    'lillebonne',
    'harfleur',
    'montivilliers',
    'gonfreville-l-orcher', 'gonfreville l orcher',
    'barentin',
    'canteleu',
    'mont-saint-aignan', 'mont saint aignan',
    'bois-guillaume', 'bois guillaume',
    'darnetal',
    'gournay-en-bray', 'gournay en bray',
    'neufchatel-en-bray', 'neufchatel en bray',
    'forges-les-eaux', 'forges les eaux',
    'valognes',
    'carentan-les-marais', 'carentan les marais',
    'saint-james', 'saint james',
    'ducey',
    'mortain-bocage', 'mortain bocage',
    'conde-sur-noireau', 'conde sur noireau',
    'aunay-sur-odon', 'aunay sur odon',
    'isigny-sur-mer', 'isigny sur mer',
    'ouistreham',
    'luc-sur-mer', 'luc sur mer',
    'cabourg',
    'dives-sur-mer', 'dives sur mer'
  ) THEN 'Normandie'

  -- ─── Bourgogne-Franche-Comté (21, 25, 39, 58, 70, 71, 89, 90) ─────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'dijon',
    'besancon',
    'macon',
    'chalon-sur-saone', 'chalon sur saone',
    'auxerre',
    'sens',
    'nevers',
    'belfort',
    'vesoul',
    'lons-le-saunier', 'lons le saunier',
    'montbeliard',
    'beaune',
    'autun',
    'montceau-les-mines', 'montceau les mines',
    'le-creusot', 'le creusot',
    'chatillon-sur-seine', 'chatillon sur seine',
    'semur-en-auxois', 'semur en auxois',
    'avallon',
    'tonnerre',
    'joigny',
    'migennes',
    'cosne-cours-sur-loire', 'cosne cours sur loire',
    'decize',
    'clamecy',
    'dole',
    'pontarlier',
    'morteau',
    'ornans',
    'saint-claude', 'saint claude',
    'morez',
    'lure',
    'luxeuil-les-bains', 'luxeuil les bains',
    'gray',
    'arbois',
    'poligny',
    'champagnole',
    'saint-amour', 'saint amour',
    'salins-les-bains', 'salins les bains',
    'audincourt',
    'valentigney',
    'bavans',
    'seloncourt',
    'fourchambault',
    'varennes-vauzelles', 'varennes vauzelles',
    'imphy',
    'hericourt',
    'paray-le-monial', 'paray le monial',
    'cluny',
    'tournus',
    'louhans',
    'gueugnon',
    'digoin',
    'saint-florentin', 'saint florentin',
    'delle',
    'beaucourt',
    'quetigny',
    'chenove',
    'longvic',
    'talant'
  ) THEN 'Bourgogne-Franche-Comté'

  -- ─── Centre-Val de Loire (18, 28, 36, 37, 41, 45) ─────────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'tours',
    'orleans',
    'bourges',
    'chartres',
    'blois',
    'chateauroux',
    'dreux',
    'joue-les-tours', 'joue les tours',
    'saint-cyr-sur-loire', 'saint cyr sur loire',
    'chambray-les-tours', 'chambray les tours',
    'la-riche', 'la riche',
    'fleury-les-aubrais', 'fleury les aubrais',
    'olivet',
    'saint-jean-de-braye', 'saint jean de braye',
    'saran',
    'ingre',
    'vierzon',
    'issoudun',
    'argenton-sur-creuse', 'argenton sur creuse',
    'le-blanc', 'le blanc',
    'la-chatre', 'la chatre',
    'romorantin-lanthenay', 'romorantin lanthenay',
    'vendome',
    'montargis',
    'gien',
    'pithiviers',
    'malesherbes',
    'nogent-le-rotrou', 'nogent le rotrou',
    'chateaudun',
    'nogent-le-roi', 'nogent le roi',
    'luce',
    'mainvilliers',
    'vernouillet',
    'luisant',
    'chateauneuf-en-thymerais', 'chateauneuf en thymerais',
    'illiers-combray', 'illiers combray',
    'courville-sur-eure', 'courville sur eure',
    'amboise',
    'loches',
    'chinon',
    'saint-pierre-des-corps', 'saint pierre des corps',
    'veretz',
    'montlouis-sur-loire', 'montlouis sur loire',
    'azay-le-rideau', 'azay le rideau',
    'montrichard', 'montrichard-val-de-cher', 'montrichard val de cher',
    'saint-aignan', 'saint aignan',
    'selles-sur-cher', 'selles sur cher',
    'mer',
    'beaugency',
    'meung-sur-loire', 'meung sur loire',
    'sully-sur-loire', 'sully sur loire',
    'chalette-sur-loing', 'chalette sur loing',
    'amilly',
    'ferrieres-en-gatinais', 'ferrieres en gatinais',
    'chateaurenard',
    'briare',
    'aubigny-sur-nere', 'aubigny sur nere',
    'sancerre',
    'saint-amand-montrond', 'saint amand montrond',
    'dun-sur-auron', 'dun sur auron',
    'mehun-sur-yevre', 'mehun sur yevre'
  ) THEN 'Centre-Val de Loire'

  -- ─── Provence-Alpes-Côte d'Azur (04, 05, 06, 13, 83, 84) ───────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'marseille',
    'nice',
    'toulon',
    'aix-en-provence', 'aix en provence',
    'avignon',
    'cannes',
    'antibes',
    'gap',
    'digne-les-bains', 'digne les bains',
    'manosque',
    'draguignan',
    'frejus',
    'hyeres',
    'martigues',
    'arles',
    'istres',
    'salon-de-provence', 'salon de provence',
    'carpentras',
    'orange',
    'grasse',
    'cagnes-sur-mer', 'cagnes sur mer',
    'le-cannet', 'le cannet',
    'mandelieu-la-napoule', 'mandelieu la napoule',
    'vallauris',
    'mougins',
    'vence',
    'menton',
    'roquebrune-cap-martin', 'roquebrune cap martin',
    'saint-laurent-du-var', 'saint laurent du var',
    'valbonne',
    'biot',
    'villeneuve-loubet', 'villeneuve loubet',
    'la-seyne-sur-mer', 'la seyne sur mer',
    'six-fours-les-plages', 'six fours les plages',
    'la-garde', 'la garde',
    'sanary-sur-mer', 'sanary sur mer',
    'bandol',
    'saint-raphael', 'saint raphael',
    'sainte-maxime', 'sainte maxime',
    'cavalaire-sur-mer', 'cavalaire sur mer',
    'saint-tropez', 'saint tropez',
    'gonfaron',
    'brignoles',
    'saint-maximin-la-sainte-baume', 'saint maximin la sainte baume',
    'aubagne',
    'la-ciotat', 'la ciotat',
    'gardanne',
    'vitrolles',
    'marignane',
    'briancon',
    'embrun',
    'sisteron',
    'forcalquier',
    'apt',
    'cavaillon',
    'l-isle-sur-la-sorgue', 'l isle sur la sorgue',
    'pertuis',
    'sorgues',
    'bollene',
    'valreas',
    'vaison-la-romaine', 'vaison la romaine',
    'castellane'
  ) THEN 'Provence-Alpes-Côte d''Azur'

  -- ─── Corse (2A, 2B) ─────────────────────────────────────────────────────
  WHEN unaccent(lower(trim(ville))) IN (
    'ajaccio',
    'bastia',
    'porto-vecchio', 'porto vecchio',
    'corte',
    'sartene',
    'propriano',
    'calvi',
    'l-ile-rousse', 'l ile rousse', 'ile rousse',
    'bonifacio',
    'biguglia',
    'borgo',
    'furiani',
    'ghisonaccia',
    'aleria',
    'algajola',
    'cargese',
    'piana',
    'evisa',
    'zonza',
    'levie',
    'solenzara',
    'moriani-plage', 'moriani plage',
    'folelli',
    'penta-di-casinca', 'penta di casinca',
    'prunelli-di-fiumorbo', 'prunelli di fiumorbo',
    'ventiseri',
    'luri',
    'pino',
    'macinaggio',
    'saint-florent', 'saint florent',
    'patrimonio',
    'oletta',
    'belgodere',
    'lumio',
    'feliceto',
    'speloncato',
    'moltifao',
    'vico',
    'cauro',
    'bastelica',
    'zicavo',
    'quenza',
    'porto'
  ) THEN 'Corse'

  ELSE region
END
WHERE ville IS NOT NULL
  AND trim(ville) <> '';
